const leftKeys=[
    {label:'(',operation:'default'},
    {label:')',operation:'default'},
    {label:'MC',operation:'MC'},
    {label:'M+',operation:'M+'},
    {label:'M-',operation:'M-'},
    {label:'MR',operation:'MR'},
    {label:'2^nd',operation:'IntFormat'},
    {label:'2^x',operation:'powerOf2'},
    {label:'x^y',operation:'x^y'},
    {label:'x²',operation:'square'},    
    {label:'e',operation:'exponentOf10'},
    {label:'e^x',operation:'powerOfe'},
    {label:'1/x',operation:'multiplicativeInverse'},
    {label:'x!',operation:'factorial'},
    {label:'y√x',operation:'y√x'},
    {label:'√x',operation:'squareRoot'},
    {label:'π',operation:'pie'},
    {label:'ln',operation:'ln'},
    {label:'Rand',operation:'random'},
    {label:'tan',operation:'tan'},
    {label:'sin',operation:'sin'},
    {label:'cos',operation:'cos'},
    {label:'Y^x',operation:'Y^x'},
    {label:'10^x',operation:'powerOf10'},
    {label:'Deg',operation:'Deg'},
    {label:'tanh',operation:'tanh'},
    {label:'sinh',operation:'sinh'},
    {label:'cosh',operation:'cosh'},
    {label:'log^y',operation:'log^y'},
    {label:'log',operation:'log'},
];

const rightKeys=[
    {label:'C',operation:'cancel'},
    {label:'del',operation:'delete'},
    {label:'%',operation:'default'},
    {label:'+',operation:'default'},
    {label:'7',operation:'default'},
    {label:'8',operation:'default'},
    {label:'9',operation:'default'},
    {label:'/',operation:'default'},
    {label:'4',operation:'default'},
    {label:'5',operation:'default'},
    {label:'6',operation:'default'},
    {label:'*',operation:'default'},
    {label:'1',operation:'default'},
    {label:'2',operation:'default'},
    {label:'3',operation:'default'},
    {label:'-',operation:'default'},
    {label:'.',operation:'default'},
    {label:'0',operation:'default'},
    {label:'=',operation:'equals'},
    {label:'+',operation:'default'},
];

export {leftKeys,rightKeys};