const leftKeys=[
    {label:'(',operation:'('},
    {label:')',operation:')'},
    {label:'MC',operation:'MC'},
    {label:'M+',operation:'M+'},
    {label:'M-',operation:'M-'},
    {label:'MR',operation:'MR'},
    {label:'2nd',operation:'2nd'},
    {label:'xy',operation:'xy'},
    {label:'x2',operation:'x2'},
    {label:'e',operation:'ex'},
    {label:'1/x',operation:'1/x'},
    {label:'x!',operation:'x!'},
    {label:'x',operation:'2nd'},
    {label:'2nd',operation:'2nd'},
    {label:'2nd',operation:'2nd'},
    {label:'2nd',operation:'2nd'},
    {label:'2nd',operation:'2nd'},
    {label:'2nd',operation:'2nd'},
    {label:'2nd',operation:'2nd'},
    {label:'2nd',operation:'2nd'},
    {label:'2nd',operation:'2nd'},
    {label:'2nd',operation:'2nd'},
    {label:'2nd',operation:'2nd'},
    {label:'2nd',operation:'2nd'},
    {label:'2nd',operation:'2nd'},
    {label:'2nd',operation:'2nd'},
    {label:'2nd',operation:'2nd'},
    {label:'2nd',operation:'2nd'},
    {label:'2nd',operation:'2nd'},
    {label:'2nd',operation:'2nd'},
];

const rightKeys=[
    {label:'C',operation:'Cancel'},
    {label:'back',operation:'delete'},
    {label:'%',operation:'%'},
    {label:'+',operation:'+'},
    {label:'7',operation:'7'},
    {label:'8',operation:'8'},
    {label:'9',operation:'9'},
    {label:'/',operation:'/'},
    {label:'4',operation:'4'},
    {label:'5',operation:'5'},
    {label:'6',operation:'6'},
    {label:'*',operation:'*'},
    {label:'1',operation:'1'},
    {label:'2',operation:'2'},
    {label:'3',operation:'3'},
    {label:'-',operation:'-'},
    {label:'.',operation:'.'},
    {label:'0',operation:'0'},
    {label:'=',operation:'='},
    {label:'+',operation:'+'},
];

export {leftKeys,rightKeys};